### ISSUE TITLE
deleted some repo !

### ISSUE THREAD

**Issue by kiaxseventh** [modulovalue/web3js_test_page#1]
hello man

thank you for this project

This repo has been removed:
https://github.com/modulovalue/bird
How to run the project now ?

**Comment by modulovalue** [comment]
Hey sry for that, there’s a discontinued  version of bird on pub.dev, it might work with the pub.dev one.

**Comment by kiaxseventh** [comment]
of course
I checked the available versions on pub dev but the problems were not resolved

continue this project please . It has a very good future

**Comment by modulovalue** [comment]
Sadly I cannot share bird anymore and I have to focus on other things, sorry for that.
If you're familiar with flutter then you should be able to switch to a different state management solution with very little trouble. The most interesting part here is the interaction between dart and js. 

@MajestyGo on twitter might be able to help you. He got this demo working a couple weeks ago.
